server:
  port: 8082

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: mooshi
    password: mooshi123
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: customer-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.mooshi.event
        spring.json.type.mapping: user.registered:com.mooshi.event.UserRegisteredEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
