server:
  port: 8086

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: mooshi
    password: mooshi123
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.mooshi.event
        spring.json.type.mapping: >
          user.registered:com.mooshi.event.UserRegisteredEvent,
          order.created:com.mooshi.event.OrderCreatedEvent,
          payment.completed:com.mooshi.event.PaymentCompletedEvent,
          order.completed:com.mooshi.event.OrderCompletedEvent

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
